

http.proxy.parametername: notused

no.nav.security.jwt:
  expirythreshold: 10 #threshold in minutes until token expires
  issuer:
    issuer1:
      discovery-url: http://localhost:${mock-oauth2-server.port}/default/.well-known/openid-configuration
      accepted_audience: default
    issuer2:
      discovery-url: http://localhost:${mock-oauth2-server.port}/default/.well-known/openid-configuration
      accepted_audience: default
logging.level:
  org.springframework: INFO
  no.nav: DEBUG
FRONTEND:
  URL: localhost
  PORT: 3000

